### PR TITLE
XY bracket for rails atop the frame

### PR DESCRIPTION
**Pull request by tomaski**
That bracket is almost plug and play: almost, in sense that it is not reusing the screws from stock bracket. Shorter ones are now needed. But since RatRig package comes with plenty of spares, that oughtn't be a problem:
Recommended lengths: 15mm closer to the frame, 10mm closer to the rail

### CODE REVIEW

**Comment by pkucmus** [comment]
This is awesome, thanks! Please allow me some time to test it. 
Also let me know how can I mention you as the author of the work once it's merged (i.e. Github link, full name, something else?).

**Comment by tomaski** [comment]
Hey, @pkucmus. Glad you like it :)

I already did some testing ;)
Although I have to admit, the tolerances are VERY tight (it's basically a
force-fit)

As for the mention: AFAIK, github will know who the author is?


pon., 27 lip 2020, 16:19 użytkownik Paweł Kucmus <notifications@github.com>
napisał:

**Comment by Turricann** [comment]
looks like this is just what i have been looking for on my RATRIG, ill give them ago and let you know how i find them A+ for the design update on this already amazing project.

**Comment by tomaski** [comment]
@Turricann it won't hurt to mention: if/when you're gonna print this part, make sure to mirror the other one instead of printing 2x (this due to how belts run)

**Comment by Turricann** [comment]
@tomaski I will be printing it at the weekend so I will let you know.

**Comment by pkucmus** [comment]
@tomaski The most important and difficult part - belt alignment is spot on. Aside from there there is one issue and one question:

1. There is an interference between the MGN rail and the Joiner 
image

2. There is some ambiguity around the spacing where the wheels are, you got rid of the 1mm "posts" the original has and now it need extra spacers, was that by design?

**Comment by tomaski** [comment]
@pkucmus 
a.d. 1) yes. if reusing the nuts that were originally used for that joiner, this part is not 1:1 swappable. But because the V-Core Pro comes with a lost of spare screws, I used one of those instead: M5x10mm

a.d. 2) yes, because depending on whether it's left or right joiner, position of the wheels change but if the joiner is mirrored, the "posts" remain on the same location. So on the mirrored side, they'd be in a place where the 2 spacers go and the wheel would be rubbing against the part. So it's either this (the posts removed) or doing two dedicated parts for L/R

**Comment by pkucmus** [comment]
a.d. 2) got it

a.d. 1) I don't think we understood each other - I'm talking about this:
image
can you see how the MGN rail is not fitting under the top of the plastic?

**Comment by tomaski** [comment]
oh, that. 
Well I measured the rail's thickness with calipers and designed the insertion point accordingly. Having printed 6 iterations of that design, I do have to admit that even though the rail fit, is was an extremely tight fit (hammering it into place with rubber mallet). If you want, I'll update the design and add some clearance

**Comment by pkucmus** [comment]
Yes, please. In most cases 0.1 clearance is enough but not too much when talking about a printed part interfacing with hardware, if not then people with less fine tuned printers "complain" (from lack of a better word). In this case the vertical edge of the MGN rail slot should have 10.0mm (10.1mm starting from the 2020 top face).

**Comment by tomaski** [comment]
@pkucmus PR updated

**Comment by Turricann** [comment]
Finally got round to fitting the top mounts and can definitely say the clearance is needed for a better fit  *** I printed original brackets*** but they do go on and off with gental perswation easly enough without the part cracking.
Just incase any one needs to know the bolts going through the bearings need to be 45mm long and 1 extra 1mm shim for the base of the stack is needed. 

And for the top I reused the flat " t nuts " and 4 of the m5 x 8mm bolts that are used to fix the frame together.

**Pull request closed without merging**
